version: "3.9"

services:
  # Expose port 8080 for Go app
  go:
    image: wengtad/godock:latest
    ports:
      - 8080:8080
    volumes:
      - ./data/projects:/root/projects

  # The username/password is root/root
  # --- For PostgreSQL ---
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data

  # --- For MariaDB ---
  # db:
  #   image: mariadb
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - ./data/db/mariadb:/var/lib/mysql

  # Expore port 8081 for Adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  cache:
    image: redis:7-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass mySecurePa33w0rd
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
